name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build:
    name: x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/checkout@v2
      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            /var/lib/docker
          key: ${{ runner.os }}-northstar

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"
          architecture: x64

      - name: Login to DockerHub
        if: (github.ref == 'refs/heads/master' || github.event_name == 'push') && github.repository == 'forgeflux-org/northstar'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: install virtualenv
        run: pip install virtualenv

      - name: Install python dependencies
        run: make env

      - name: Run database migrations
        run: make migrate

      - name: Run linting
        run: make lint

      - name: Run tests
        run: make test

      - name: Prepare test coverage report
        run: make coverage

      - name: Create docker image
        run: make docker

      - name: Publish docker image
        if: (github.ref == 'refs/heads/master' || github.event_name == 'push') && github.repository == 'forgeflux-org/northstar'
        run: docker push forgedfed/northstar

      - name: Generate documentation
        run: make doc

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master' || github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: northstar/static/docs/openapi/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
